### ISSUE TITLE
Flysky el18 Switch Funktion lost

### ISSUE THREAD

**Issue by Boxxxer64** [EdgeTX/edgetx#6112]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### What part of EdgeTX is the focus of this bug?

Transmitter firmware

### Current Behavior

Flysky EL18 EdgeTX 2.11RC3. The switches stop working at random intervals. Sometimes for 20 minutes, sometimes for an hour. It's very dangerous if the copter won't let you disarm.

### Expected Behavior

Flysky EL18 EdgeTX 2.11RC3. The switches stop working at random intervals. Sometimes for 20 minutes, sometimes for an hour. It's very dangerous if the copter won't let you disarm.

### Steps To Reproduce

Dont know 

### Version

2.11.0-rc

### Transmitter

Flysky EL18

### Operating System (OS)

macOS

### OS Version

Latest

**Comment by Boxxxer64** [comment]
Video

**Comment by Boxxxer64** [comment]
https://youtube.com/shorts/sNU78yLwD00?si=tDT54h76nSo4V6-q

**Comment by richardclli** [comment]
The symptom can be related to hardware cabling connectivity problem, did you check this?
Can downgrading to 2.10 solves the problem?

**Comment by Boxxxer64** [comment]
I don't think it's a hardware issue. All switches are affected, and the rear ones are connected to a different board. I'll have to test whether a downgrade fixes the problem. Apparently, there was a problem with 2.11 that was supposed to be fixed with RC3. I'll try upgrading to 2.10 in the next few days.

**Comment by Boxxxer64** [comment]
With 2.10.6 The hole day no Problem. No Switch Problem.

**Comment by richardclli** [comment]
Interesting though, let me test this when I have spare time.

**Comment by richardclli** [comment]
Is the symptom the same as #6200?

**Comment by richardclli** [comment]
@RustyWraith Follow up your problem here

**Comment by richardclli** [comment]
Please test the release version 2.11.0 to see if the problem persists.  Or wait for the 2.11.1 releases, should be out soon.

**Comment by RustyWraith** [comment]
I can confirm the issue with 2.11.0 and NV14

**Comment by richardclli** [comment]
> I can confirm the issue with 2.11.0 and NV14.

Can the problem be reproduced by switching on the radio and wait for 1-2 hours?

**Comment by richardclli** [comment]
Check if 2.11.1 fixes the problem.  There are quite a few critical bugs and fixed in 2.11.1, so not sure if the problem is gone or not.

**Comment by richardclli** [comment]
> > > I can confirm the issue with 2.11.0 and NV14.
> > 
> > Can the problem be reproduced by switching on the radio and wait for 1-2 hours doing nothing? Or requires one to move.the gimbals/switches to reproduce?
> 
> I've kept the radio on for 3 hours without touching anything. Switches were working.

So one must operate the radio to repeat the problem, right?

**Comment by RustyWraith** [comment]
> So one must operate the radio to repeat the problem, right?

I've tested the radio two times for about 5-6 hours total. It was sitting on the desk on batteries without any input.
Worked fine. It could be just luck, though. The pattern to reproduce is unknown for me.

**Comment by RustyWraith** [comment]
> Check if 2.11.1 fixes the problem. There are quite a few critical bugs and fixed in 2.11.1, so not sure if the problem is gone or not.

I've installed todays nightly via ETX buddy. I'll report if issue persist or not.

**Comment by RustyWraith** [comment]
Can confirm the bug persists in 2.11.1.

**Comment by gagarinlg** [comment]
I have an EL18 running since 16 hours now, with an external ELRS module connected and the error did not happen.
Could someone please share their radio config, model and widgets with me, so that I can test that specific setup?

**Comment by RustyWraith** [comment]
Please, use my config from https://github.com/EdgeTX/edgetx/issues/6200

**Comment by richardclli** [comment]
Just remember one thing that worth to check.  So for those who are able to reproduce this.  Please reproduce the problem and check the hardware debug screen and see if the switches all malfunctioned?  Or moving sa will show sb moving, etc.

**Comment by RustyWraith** [comment]
As I remember, all switches are stuck in the position they had at the time of the bug event.
Can it be, that the bug is only happens, when the INPUTS tab is not completely empty?

**Comment by jwidess** [comment]
Just confirmed on my [hardware modded NV14](https://docs.google.com/document/d/1gauT_LnciE42GizPJLEwAzpfjIcEYqL82MlzOYP5KFQ) I am experiencing the same problems. After some amount of time, all switches stop working, but gimbals remain. In the _Debug->Keys_ menu all inputs show absolutely no change, _Debug->Analogs_ however work fine.
FW: edgetx-nv14
VERS: **v2.12.0** "Queen Anne's Revenge"
DATE: 2026-03-28
External Module: HM ES24TX Pro V4.0
I will revert to **v2.10.6** for the time being. :disappointed:
